### ISSUE TITLE
reporting ui doesn't show vigraha logo

### ISSUE THREAD

**Issue by rajithd** [rajithd/vigraha#2]

**Comment by dslas4ever** [comment]
rajja,
ekka aei haddana wei wage,
logo ekka ganna nathi seen ekkak thiyenna?

On Tue, Jul 3, 2012 at 7:17 PM, Rajith Delantha <
reply@reply.github.com

> wrote:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rajithd/vigraha/issues/2

## 

Lasantha Perera
SLIIT
